# Generated by Django 5.1.7 on 2025-05-22 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("codificadores", "0001_initial"),
        ("episodio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro_Operatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_operacion", models.DateField()),
                ("es_reintervencion", models.BooleanField()),
                (
                    "escala_evaluacion_resultados_glasgow",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(15),
                        ]
                    ),
                ),
                ("estado_egreso", models.BooleanField()),
                ("observaciones", models.CharField(blank=True, max_length=512)),
                (
                    "episodio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodio_registro_operatorio",
                        to="episodio.episodio",
                    ),
                ),
            ],
            options={
                "verbose_name": "registros operatorios",
            },
        ),
        migrations.CreateModel(
            name="Rasgos_Clinicos_Operatorios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codificador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codificador_operatorio",
                        to="codificadores.codificadores",
                    ),
                ),
                (
                    "registro_operatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasgos_clinicos_operatorios",
                        to="registro_operatorio.registro_operatorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "rasgo clinico operatorio",
                "verbose_name_plural": "rasgos clinicos operatorios",
            },
        ),
        migrations.CreateModel(
            name="Registro_Posoperatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("tiempo_transcurrido", models.IntegerField()),
                ("escala_pronostica_oslo_posoperatoria", models.IntegerField()),
                ("recurrencia_hematoma", models.BooleanField()),
                (
                    "gradacion_pronostica_para_recurrencia_hsc_unilateral",
                    models.IntegerField(),
                ),
                (
                    "registro_operatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registro_operatorio_posoperatorio",
                        to="registro_operatorio.registro_operatorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro posoperatorio",
                "verbose_name_plural": "registros posoperatorios",
            },
        ),
    ]
