# Generated by Django 5.1.7 on 2025-05-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro_operatorio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro_operatorio",
            name="fecha_operacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registro_posoperatorio",
            name="escala_pronostica_oslo_posoperatoria",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registro_posoperatorio",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registro_posoperatorio",
            name="gradacion_pronostica_para_recurrencia_hsc_unilateral",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registro_posoperatorio",
            name="recurrencia_hematoma",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registro_posoperatorio",
            name="tiempo_transcurrido",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
