def prepare_headers(selected_fields):
    field_names = {
        # Historia Clínica
        "numero": "Número HC",
        "seudonimo": "Seudónimo",
        "nombre": "Nombre",
        "apellidos": "Apellidos",
        "edad": "Edad",
        "sexo": "Sexo",
        "historial_trauma_craneal": "Historial Trauma Craneal",
        "manualidad": "Manualidad",
        "antecedentes_familiares": "Antecedentes Familiares",
        # Episodio
        "inicio": "Episodio - Inicio",
        "fecha_alta": "Episodio - Fecha Alta",
        "tiempo_estadia": "Episodio - Tiempo Estadia",
        "estado_al_egreso": "Episodio - Estado Egreso",
        "tiempo_antecedente": "Episodio - Tiempo Antecedente",
        "descripcion_antecedente": "Episodio - Descripción Antecedente",
        "edad_paciente": "Episodio - Edad Paciente",
        "observaciones": "Episodio - Observaciones",
        # Rasgos Clínicos Globales
        "notas": "RCG - Notas",
        "tiempo": "RCG - Tiempo",
        "notas_rasgos_clinicos_episodio": "RCE - Notas",
        # Registro Operatorio
        "fecha_operacion": "Registro Op. - Fecha Operación",
        "es_reintervencion": "Registro Op. - Reintervención",
        "escala_evaluacion_resultados_glasgow": "Registro Op. - Escala Glasgow",
        "estado_egreso": "Registro Op. - Estado Egreso",
        "observaciones_registro_operatorio": "Registro Op. - Observaciones",
        # Registro Posoperatorio
        "fecha": "Posoperatorio - Fecha",
        "tiempo_transcurrido": "Posoperatorio - Tiempo Transcurrido",
        "escala_pronostica_oslo_posoperatoria": "Posoperatorio - Escala Oslo",
        "recurrencia_hematoma": "Posoperatorio - Recurrencia Hematoma",
        "gradacion_pronostica_para_recurrencia_hsc_unilateral": "Posoperatorio - Gradación Recurrencia",
        # Hematoma Subdural
        "escala_glasgow_ingreso": "Hematoma - Escala Glasgow Ingreso",
        "escala_mcwalder": "Hematoma - Escala McWalder",
        "escala_gordon_firing": "Hematoma - Escala Gordon Firing",
        "escala_pronostica_oslo_preoperatoria": "Hematoma - Escala Oslo Preop",
        "escala_nomura": "Hematoma - Escala Nomura",
        "escala_nakagushi": "Hematoma - Escala Nakagushi",
        "valor_longitud": "Hematoma - Longitud",
        "valor_diametro": "Hematoma - Diámetro",
        "valor_altura": "Hematoma - Altura",
        "volumen_tada": "Hematoma - Volumen TADA",
        "volumen": "Hematoma - Volumen",
        "grupo_volumen": "Hematoma - Grupo Volumen",
        "grupo_volumen_residual_posoperatorio": "Hematoma - Grupo Volumen Residual",
        "diametro_capa": "Hematoma - Diámetro Capa",
        "diametro_mayor_transverso": "Hematoma - Diámetro Mayor Transverso",
        "grupo_diametro": "Hematoma - Grupo Diámetro",
        "presencia_membrana": "Hematoma - Presencia Membrana",
        "tipo_membrana": "Hematoma - Tipo Membrana",
        "localización": "Hematoma - Localización",
        "topografia": "Hematoma - Topografía",
        "desviacion_linea_media": "Hematoma - Desviación Línea Media",
        "metodo_lectura": "Hematoma - Método Lectura",
        "observaciones_hematoma": "Hematoma - Observaciones",
        # Codificadores Globales
        "nombre_codificadores_globales": "RCG - Nombre Codificador",
        "nombre_corto": "RCG - Nombre Corto",
        "descripcion": "RCG - Descripción",
        "clasificacion": "RCG - Clasificación",
        # Codificadores Episodio
        "nombre_codificador_episodio": "RCE - Nombre Codificador",
        "nombre_corto_codificador_episodio": "RCE - Nombre Corto",
        "descripcion_codificador_episodio": "RCE - Descripción",
        "clasificacion_codificador_episodio": "RCE - Clasificación",
        # Codificadores Operatorios
        "nombre_codificador_operatorio": "Rasgo Op. - Nombre Codificador",
        "nombre_corto_codificador_operatorio": "Rasgo Op. - Nombre Corto",
        "descripcion_codificador_operatorio": "Rasgo Op. - Descripción",
        "clasificacion_codificador_operatorio": "Rasgo Op. - Clasificación",
    }

    return [field_names.get(field, field) for field in selected_fields]
