# Generated by Django 5.1.7 on 2025-05-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codificadores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codificadores",
            name="descripcion",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="codificadores",
            name="nombre_corto",
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
