# Generated by Django 5.1.7 on 2025-05-29 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hematoma", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="escala_mcwalder",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
    ]
