# Generated by Django 5.1.7 on 2025-05-29 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hematoma", "0002_alter_hematoma_subdural_escala_mcwalder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="escala_pronostica_oslo_preoperatoria",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="grupo_diametro",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="grupo_volumen",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="grupo_volumen_residual_posoperatorio",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="metodo_lectura",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="tipo_membrana",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="topografia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="valor_altura",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="valor_diametro",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="valor_longitud",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
