# Generated by Django 5.1.7 on 2025-05-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hematoma",
            "0003_alter_hematoma_subdural_escala_pronostica_oslo_preoperatoria_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="localización",
            field=models.IntegerField(),
        ),
    ]
