# Generated by Django 5.1.7 on 2025-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hematoma", "0004_alter_hematoma_subdural_localización"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hematoma_subdural",
            name="observaciones",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
