# Generated by Django 5.1.7 on 2025-03-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestionar_historia_clinica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episodio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateField()),
                ("fecha_alta", models.DateField()),
                ("tiempo_estadia", models.IntegerField()),
                ("estado_al_egreso", models.BooleanField()),
                ("tiempo_antecedente", models.IntegerField()),
                ("descripcion_antecedente", models.CharField(max_length=255)),
                ("edad_paciente", models.IntegerField()),
                ("observaciones", models.CharField(blank=True, max_length=512)),
                (
                    "historia_clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodios",
                        to="gestionar_historia_clinica.historia_clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "episodio",
                "verbose_name_plural": "episodios",
            },
        ),
    ]
