# Generated by Django 5.1.7 on 2025-03-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codificadores", "0001_initial"),
        ("gestionar_episodio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rasgos_Clinicos_Episodio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo", models.IntegerField()),
                ("notas", models.CharField(max_length=512)),
                (
                    "codificador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasgos_episodios",
                        related_query_name="rasgo_episodio",
                        to="codificadores.codificadores",
                    ),
                ),
                (
                    "episodio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodio",
                        to="gestionar_episodio.episodio",
                    ),
                ),
            ],
            options={
                "verbose_name": "rasgo clinico del episodio",
                "verbose_name_plural": "resgos clinicos del episodio",
            },
        ),
    ]
