# Generated by Django 5.1.7 on 2025-05-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("codificadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="historia_clinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                ("seudonimo", models.CharField(max_length=127)),
                ("nombre", models.CharField(max_length=32)),
                ("apellidos", models.CharField(max_length=63)),
                ("edad", models.PositiveIntegerField()),
                ("sexo", models.BooleanField()),
                ("historial_trauma_craneal", models.BooleanField()),
                ("manualidad", models.BooleanField()),
                ("antecedentes_familiares", models.BooleanField()),
            ],
            options={
                "verbose_name": "historia clínica",
                "verbose_name_plural": "historias clínicas",
            },
        ),
        migrations.CreateModel(
            name="Rasgos_Clinicos_Globales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notas", models.CharField(max_length=512)),
                (
                    "codificador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasgos_globales",
                        related_query_name="rasgo_global",
                        to="codificadores.codificadores",
                    ),
                ),
                (
                    "historia_clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_clinica",
                        to="hc.historia_clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "rasgo clinico global",
                "verbose_name_plural": "rasgos clinicos globales",
            },
        ),
    ]
