# Generated by Django 5.1.7 on 2025-05-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historia_clinica",
            name="antecedentes_familiares",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historia_clinica",
            name="manualidad",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
