# Generated by Django 5.1.7 on 2025-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hc", "0002_alter_historia_clinica_antecedentes_familiares_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rasgos_clinicos_globales",
            name="notas",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
