# Generated by Django 5.1.7 on 2025-03-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="historia_clinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                ("seudonimo", models.CharField(max_length=127)),
                ("nombre", models.CharField(max_length=32)),
                ("apellidos", models.CharField(max_length=63)),
                ("edad", models.PositiveIntegerField()),
                ("sexo", models.BooleanField()),
                ("historial_trauma_craneal", models.BooleanField()),
                ("manualidad", models.BooleanField()),
                ("antecedentes_familiares", models.BooleanField()),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
            },
        ),
    ]
