# Generated by Django 5.1.7 on 2025-03-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codificadores", "0001_initial"),
        ("gestionar_historia_clinica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rasgos_Clinicos_Globales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notas", models.CharField(max_length=512)),
                (
                    "codificador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasgos_globales",
                        related_query_name="rasgo_global",
                        to="codificadores.codificadores",
                    ),
                ),
                (
                    "historia_clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_clinica",
                        to="gestionar_historia_clinica.historia_clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "rasgo clinico global",
                "verbose_name_plural": "resgos clinicos globales",
            },
        ),
    ]
