# Generated by Django 5.1.7 on 2025-05-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("codificadores", "0001_initial"),
        ("hc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episodio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateField()),
                ("fecha_alta", models.DateField()),
                ("tiempo_estadia", models.IntegerField()),
                ("estado_al_egreso", models.BooleanField()),
                ("tiempo_antecedente", models.IntegerField()),
                ("descripcion_antecedente", models.CharField(max_length=255)),
                ("edad_paciente", models.IntegerField()),
                ("observaciones", models.CharField(blank=True, max_length=512)),
                (
                    "historia_clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_clinica_episodio",
                        to="hc.historia_clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "episodio",
                "verbose_name_plural": "episodios",
            },
        ),
        migrations.CreateModel(
            name="Rasgos_Clinicos_Episodio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo", models.IntegerField()),
                ("notas", models.CharField(max_length=512)),
                (
                    "codificador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasgos_episodios",
                        related_query_name="rasgo_episodio",
                        to="codificadores.codificadores",
                    ),
                ),
                (
                    "episodio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodio_rce",
                        to="episodio.episodio",
                    ),
                ),
            ],
            options={
                "verbose_name": "rasgo clinico del episodio",
                "verbose_name_plural": "resgos clinicos del episodio",
            },
        ),
    ]
