# Generated by Django 5.1.7 on 2025-04-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("codificadores", "0001_initial"),
        ("episodio", "0001_initial"),
        ("hc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="historia_clinica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historia_clinica_episodio",
                to="hc.historia_clinica",
            ),
        ),
        migrations.AddField(
            model_name="rasgos_clinicos_episodio",
            name="codificador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rasgos_episodios",
                related_query_name="rasgo_episodio",
                to="codificadores.codificadores",
            ),
        ),
        migrations.AddField(
            model_name="rasgos_clinicos_episodio",
            name="episodio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodio_rce",
                to="episodio.episodio",
            ),
        ),
    ]
