# Generated by Django 5.1.7 on 2025-05-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodio",
            name="descripcion_antecedente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="episodio",
            name="fecha_alta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episodio",
            name="inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episodio",
            name="observaciones",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="episodio",
            name="tiempo_antecedente",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episodio",
            name="tiempo_estadia",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
