# Generated by Django 5.1.7 on 2025-05-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodio", "0002_alter_episodio_descripcion_antecedente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rasgos_clinicos_episodio",
            name="tiempo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
