# Generated by Django 5.1.7 on 2025-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodio", "0003_alter_rasgos_clinicos_episodio_tiempo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodio",
            name="estado_al_egreso",
            field=models.BooleanField(null=True),
        ),
    ]
