# Generated by Django 5.1.7 on 2025-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodio", "0004_alter_episodio_estado_al_egreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rasgos_clinicos_episodio",
            name="notas",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
